// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkshopFlow.Data;

#nullable disable

namespace WorkshopFlow.Migrations
{
    [DbContext(typeof(WorkshopFlowContext))]
    [Migration("20260620154620_FilterRoutingStepUniqueIndex")]
    partial class FilterRoutingStepUniqueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RolesCapabilities", b =>
                {
                    b.Property<int>("CapabilitiesId")
                        .HasColumnType("int");

                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.HasKey("CapabilitiesId", "RolesId");

                    b.HasIndex("CapabilitiesId")
                        .HasDatabaseName("IX_RolesCapabilities_CapabilityId");

                    b.HasIndex("RolesId");

                    b.ToTable("RolesCapabilities");
                });

            modelBuilder.Entity("WorkshopFlow.Models.BomLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComponentItemId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProducedItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("UnitOfMeasureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnitOfMeasureId");

                    b.HasIndex(new[] { "ComponentItemId" }, "IX_BomLines_ComponentItemId");

                    b.HasIndex(new[] { "ProducedItemId" }, "IX_BomLines_ProducedItemId");

                    b.HasIndex(new[] { "ProducedItemId", "ComponentItemId" }, "UQ_BomLines_ProducedItem_ComponentItem")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("BomLines");
                });

            modelBuilder.Entity("WorkshopFlow.Models.Capability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UQ_Capabilities_Name")
                        .IsUnique();

                    b.ToTable("Capabilities");
                });

            modelBuilder.Entity("WorkshopFlow.Models.InventoryTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatedByUserId" }, "IX_InventoryTransactions_CreatedByUserId");

                    b.HasIndex(new[] { "ItemId" }, "IX_InventoryTransactions_ItemId");

                    b.HasIndex(new[] { "TransactionType" }, "IX_InventoryTransactions_TransactionType");

                    b.HasIndex(new[] { "WorkOrderId" }, "IX_InventoryTransactions_WorkOrderId");

                    b.ToTable("InventoryTransactions");
                });

            modelBuilder.Entity("WorkshopFlow.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("StockQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("UnitOfMeasureId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("WeightPerUoM")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("WeightUoMId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WeightUoMId");

                    b.HasIndex(new[] { "ItemType" }, "IX_Items_ItemType");

                    b.HasIndex(new[] { "UnitOfMeasureId" }, "IX_Items_UnitOfMeasureId");

                    b.HasIndex(new[] { "ItemCode" }, "UQ_Items_ItemCode")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("WorkshopFlow.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("WorkstationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "WorkstationId" }, "IX_Machines_WorkstationId");

                    b.HasIndex(new[] { "Code" }, "UQ_Machines_Code")
                        .IsUnique();

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("WorkshopFlow.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UQ_Roles_Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("WorkshopFlow.Models.RoutingStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MachineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProducedItemId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("WorkstationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex(new[] { "WorkstationId" }, "IX_RoutingSteps_WorkstationId");

                    b.HasIndex(new[] { "ProducedItemId", "Sequence" }, "UQ_RoutingSteps_ProducedItem_Sequence")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("RoutingSteps");
                });

            modelBuilder.Entity("WorkshopFlow.Models.UnitOfMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UQ_UnitOfMeasures_Name")
                        .IsUnique();

                    b.HasIndex(new[] { "Symbol" }, "UQ_UnitOfMeasures_Symbol")
                        .IsUnique();

                    b.ToTable("UnitOfMeasures");
                });

            modelBuilder.Entity("WorkshopFlow.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "IX_Users_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "RoleId" }, "IX_Users_RoleId");

                    b.HasIndex(new[] { "Username" }, "IX_Users_Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WorkshopFlow.Models.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PlannedEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlannedStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProducedItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WorkOrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatedByUserId" }, "IX_WorkOrders_CreatedByUserId");

                    b.HasIndex(new[] { "ProducedItemId" }, "IX_WorkOrders_ProducedItemId");

                    b.HasIndex(new[] { "Status" }, "IX_WorkOrders_Status");

                    b.HasIndex(new[] { "WorkOrderCode" }, "UQ_WorkOrders_WorkOrderCode")
                        .IsUnique();

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("WorkshopFlow.Models.WorkOrderOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoutingStepId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex(new[] { "RoutingStepId" }, "IX_WorkOrderOperations_RoutingStepId");

                    b.HasIndex(new[] { "Status" }, "IX_WorkOrderOperations_Status");

                    b.HasIndex(new[] { "WorkOrderId" }, "IX_WorkOrderOperations_WorkOrderId");

                    b.HasIndex(new[] { "WorkOrderId", "Sequence" }, "UQ_WorkOrderOperations_WorkOrder_Sequence")
                        .IsUnique();

                    b.ToTable("WorkOrderOperations");
                });

            modelBuilder.Entity("WorkshopFlow.Models.Workstation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Code" }, "UQ_Workstations_Code")
                        .IsUnique();

                    b.ToTable("Workstations");
                });

            modelBuilder.Entity("RolesCapabilities", b =>
                {
                    b.HasOne("WorkshopFlow.Models.Capability", null)
                        .WithMany()
                        .HasForeignKey("CapabilitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkshopFlow.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkshopFlow.Models.BomLine", b =>
                {
                    b.HasOne("WorkshopFlow.Models.Item", "ComponentItem")
                        .WithMany("UsedInBomLines")
                        .HasForeignKey("ComponentItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_BomLines_ComponentItemId");

                    b.HasOne("WorkshopFlow.Models.Item", "ProducedItem")
                        .WithMany("ProducedBomLines")
                        .HasForeignKey("ProducedItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_BomLines_ProducedItemId");

                    b.HasOne("WorkshopFlow.Models.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_BomLines_UnitOfMeasureId");

                    b.Navigation("ComponentItem");

                    b.Navigation("ProducedItem");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("WorkshopFlow.Models.InventoryTransaction", b =>
                {
                    b.HasOne("WorkshopFlow.Models.User", "CreatedBy")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_InventoryTransactions_CreatedByUserId");

                    b.HasOne("WorkshopFlow.Models.Item", "Item")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_InventoryTransactions_ItemId");

                    b.HasOne("WorkshopFlow.Models.WorkOrder", "WorkOrder")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_InventoryTransactions_WorkOrderId");

                    b.Navigation("CreatedBy");

                    b.Navigation("Item");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("WorkshopFlow.Models.Item", b =>
                {
                    b.HasOne("WorkshopFlow.Models.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany("Items")
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Items_UnitOfMeasureId");

                    b.HasOne("WorkshopFlow.Models.UnitOfMeasure", "WeightUoM")
                        .WithMany("WeightItems")
                        .HasForeignKey("WeightUoMId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Items_WeightUoMId");

                    b.Navigation("UnitOfMeasure");

                    b.Navigation("WeightUoM");
                });

            modelBuilder.Entity("WorkshopFlow.Models.Machine", b =>
                {
                    b.HasOne("WorkshopFlow.Models.Workstation", "Workstation")
                        .WithMany("Machines")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Machines_WorkstationId");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("WorkshopFlow.Models.RoutingStep", b =>
                {
                    b.HasOne("WorkshopFlow.Models.Machine", "Machine")
                        .WithMany("RoutingSteps")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_RoutingSteps_MachineId");

                    b.HasOne("WorkshopFlow.Models.Item", "ProducedItem")
                        .WithMany("RoutingSteps")
                        .HasForeignKey("ProducedItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RoutingSteps_ProducedItemId");

                    b.HasOne("WorkshopFlow.Models.Workstation", "Workstation")
                        .WithMany("RoutingSteps")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RoutingSteps_WorkstationId");

                    b.Navigation("Machine");

                    b.Navigation("ProducedItem");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("WorkshopFlow.Models.User", b =>
                {
                    b.HasOne("WorkshopFlow.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Users_RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WorkshopFlow.Models.WorkOrder", b =>
                {
                    b.HasOne("WorkshopFlow.Models.User", "CreatedBy")
                        .WithMany("CreatedWorkOrders")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_WorkOrders_CreatedByUserId");

                    b.HasOne("WorkshopFlow.Models.Item", "ProducedItem")
                        .WithMany("WorkOrders")
                        .HasForeignKey("ProducedItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_WorkOrders_ProducedItemId");

                    b.Navigation("CreatedBy");

                    b.Navigation("ProducedItem");
                });

            modelBuilder.Entity("WorkshopFlow.Models.WorkOrderOperation", b =>
                {
                    b.HasOne("WorkshopFlow.Models.User", "AssignedTo")
                        .WithMany("AssignedOperations")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_WorkOrderOperations_AssignedToUserId");

                    b.HasOne("WorkshopFlow.Models.RoutingStep", "RoutingStep")
                        .WithMany("WorkOrderOperations")
                        .HasForeignKey("RoutingStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_WorkOrderOperations_RoutingStepId");

                    b.HasOne("WorkshopFlow.Models.WorkOrder", "WorkOrder")
                        .WithMany("Operations")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_WorkOrderOperations_WorkOrderId");

                    b.Navigation("AssignedTo");

                    b.Navigation("RoutingStep");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("WorkshopFlow.Models.Item", b =>
                {
                    b.Navigation("InventoryTransactions");

                    b.Navigation("ProducedBomLines");

                    b.Navigation("RoutingSteps");

                    b.Navigation("UsedInBomLines");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("WorkshopFlow.Models.Machine", b =>
                {
                    b.Navigation("RoutingSteps");
                });

            modelBuilder.Entity("WorkshopFlow.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("WorkshopFlow.Models.RoutingStep", b =>
                {
                    b.Navigation("WorkOrderOperations");
                });

            modelBuilder.Entity("WorkshopFlow.Models.UnitOfMeasure", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("WeightItems");
                });

            modelBuilder.Entity("WorkshopFlow.Models.User", b =>
                {
                    b.Navigation("AssignedOperations");

                    b.Navigation("CreatedWorkOrders");

                    b.Navigation("InventoryTransactions");
                });

            modelBuilder.Entity("WorkshopFlow.Models.WorkOrder", b =>
                {
                    b.Navigation("InventoryTransactions");

                    b.Navigation("Operations");
                });

            modelBuilder.Entity("WorkshopFlow.Models.Workstation", b =>
                {
                    b.Navigation("Machines");

                    b.Navigation("RoutingSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
